### ISSUE TITLE
Paint and Words Failed to Start (Submitted on Paint and Words)

### ISSUE THREAD

**Issue by timothybruggeman** [sugarlabs/paint-activity#28]
In SOAS, Paint failed to start. Words failed to start. When opening up the application, it loads a blank screen as if the application is loading, but a grey box appears that says application failed to start.

Furthermore, when the Paint icon was clicked in the main menu, it changed the color of the icon to indicate that the program had been used. When Words was clicked in the main menu, the icon did not change color.

**Comment by quozl** [comment]
Works for me.  Not enough information.  What version of SoaS?  What version of Paint?  What was found in the Log activity for Paint?

**Comment by timothybruggeman** [comment]
I was using whatever was put on the Sugar Website as of November 19, 2017. I noticed there have not been too many changes since then on GitHub, but maybe this was a one-time issue from a bad install. The log said that paint ran, so it was a bit confusing.

**Comment by quozl** [comment]
Paint-65 is in `Fedora-SoaS-Live-x86_64-27-1.6.iso` and fails to start.  The log shows the problem was the one fixed in https://github.com/sugarlabs/paint-activity/commit/c309fa3940a27f8e9a4d4ca41a70c5efb6d0281c back in February 2017.  So please upgrade Paint activity, thanks.
