### ISSUE TITLE
New Tagged Release

### ISSUE THREAD

**Issue by sparshg** [sugarlabs/paint-activity#40]
@chimosky Can we make a new release here? needed for the data-checkers in this repo. Thanks

**Comment by quozl** [comment]
@sparshg, what is stopping you from doing this?  The activity is due for a release, in that it has fix commits on top of previous release.  Procedure here; https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#checklist---maintainer

**Comment by sparshg** [comment]
Sure I will make a PR for the release too
